### ISSUE TITLE
ARTINALI License

### ISSUE THREAD

**Issue by juliengs** [karthikp-ubc/Artinali#1]
The ARTINALI license refers to LLFI and should instead refer to ARTINALI, Copyright 2016-2017.
I can fix it.

**Comment by karthikp-ubc** [comment]
Yes, please fix it. Thanks,

- Karthik

**Comment by juliengs** [comment]
OK, is it OK to convert to TXT, as it doesn't contain formatting? I just used LibreOffice to edit the .rtf and the result is a mess...

**Comment by karthikp-ubc** [comment]
Yup
